pandoc ^
1.0.introduction.md        ^
1.1.features.md            ^
1.2.terminology.md         ^
1.3.requirements.md        ^
1.4.architecture.md        ^
2.0.installation.md        ^
2.1.install_server.md      ^
2.2.install_agent.md       ^
3.0.getting_started.md     ^
3.1.inspect_data.md        ^
3.2.create_parser.md       ^
3.3.create_table.md        ^
3.4.create_index.md        ^
3.5.import_data.md         ^
3.6.query_tutorial.md      ^
3.7.create_dashboard.md    ^
4.0.home.md                ^
5.0.dashboard.md           ^
5.1.presets.md             ^
5.2.widget_types.md        ^
5.3.widget_wizard.md       ^
6.0.account_mgmt.md        ^
6.1.authorization.md       ^
6.2.accounts.md            ^
6.3.groups.md              ^
7.0.audit.md               ^
8.0.query.md               ^
8.1.adhoc_query.md         ^
8.2.stream_query.md        ^
8.3.schedule_query.md      ^
8.4.saved_result.md        ^
8.5.background_query.md    ^
9.0.logger.md              ^
9.1.logger_types.md        ^
9.2.local_loggers.md       ^
9.3.sentry.md              ^
10.0.table_mgmt.md         ^
10.1.table.md              ^
10.2.index.md              ^
11.0.license.md            ^
12.0.regex.md              ^
13.0.system.md             ^
13.1.parsers.md            ^
13.10.federation.md        ^
13.2.transformers.md       ^
13.3.ftp.md                ^
13.4.ssh.md                ^
13.5.jdbc.md               ^
13.6.hdfs.md               ^
13.7.apikey.md             ^
13.8.crypto.md             ^
13.9.cache.md              ^
--toc --toc-depth=2 --template=user.tex --latex-engine=xelatex -V geometry:"top=3.5cm, bottom=3.5cm, left=2.5cm, right=2.5cm" -s -o logpresso_user_manual.pdf