pandoc ^
1.1.araqne_setup_monitoring.md ^
1.2.araqne_core.md ^
1.3.webserver.md ^
1.4.license.md ^
1.5.benchmark.md ^
2.1.client_tools.md ^
3.1.accounting.md ^
3.2.query.md ^
3.3.table.md ^
3.4.crypto.md ^
3.5.import.md ^
3.6.parser.md ^
3.7.index.md ^
3.8.cache.md ^
3.9.globals.md ^
3.10.backup_restore.md ^
3.11.ftp_profile.md ^
3.12.jdbc_profile.md ^
3.13.ssh_profile.md ^
3.14.node_profile.md ^
4.1.logapi.md ^
5.1.log_filter.md ^
6.1.managed_logger.md ^
7.1.log_output.md ^
8.1.query_manage.md ^
9.1.alert_config.md ^
10.1.excel_external.md ^
11.1.hdfs_connecter.md ^
--toc --toc-depth=2 --template=cli.tex --latex-engine=xelatex -V geometry:"top=3.5cm, bottom=3.5cm, left=2.5cm, right=2.5cm" -s -o logpresso_cli_manual.pdf